import process from 'node:process';globalThis._importMeta_={url:import.meta.url,env:process.env};import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/node-fetch-native@1.6.4/node_modules/node-fetch-native/dist/polyfill.cjs';
export { c as closePrerenderer, l as localFetch } from './chunks/runtime.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/node.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/destr@2.0.3/node_modules/destr/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/unenv@1.9.0/node_modules/unenv/runtime/fetch/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/klona@2.0.6/node_modules/klona/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/scule@1.3.0/node_modules/scule/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/defu@6.1.4/node_modules/defu/dist/defu.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/ohash@1.1.3/node_modules/ohash/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/ufo@1.5.3/node_modules/ufo/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/unstorage@1.10.2_ioredis@5.4.1/node_modules/unstorage/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/unstorage@1.10.2_ioredis@5.4.1/node_modules/unstorage/drivers/fs.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/unstorage@1.10.2_ioredis@5.4.1/node_modules/unstorage/drivers/fs-lite.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/radix3@1.1.2/node_modules/radix3/dist/index.mjs';
import 'node:async_hooks';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/vinxi@0.3.12_@opentelemetry+api@1.9.0/node_modules/vinxi/lib/app-fetch.js';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/vinxi@0.3.12_@opentelemetry+api@1.9.0/node_modules/vinxi/lib/app-manifest.js';
import 'node:fs';
import 'node:url';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/pathe@1.1.2/node_modules/pathe/dist/index.mjs';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/solid-js@1.8.18/node_modules/solid-js/dist/server.js';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/solid-js@1.8.18/node_modules/solid-js/web/dist/server.js';
import 'file:///Users/andrew/Documents/Dev/Projects/andrewnathanco/github/proj-ancgames/mural/code/node_modules/.pnpm/solid-js@1.8.18/node_modules/solid-js/web/storage/dist/storage.js';
//# sourceMappingURL=index.mjs.map
