version: "3"
services:
  mural:
    image: andyrewco/mural:$VERSION
    env_file:
      - ".env"
    environment:
      - DATABASE_FILE=/go/src/app/mural.db
      - VERSION=$VERSION
    volumes:
      - ./mural.db:/go/src/app/mural.db
    networks:
      - mural_default
    ports:
      - "1323:1323"

networks:
  mural_default:
    driver: overlay
    attachable: true
