version: "3"
services:
  mural_$VERSION:
    image: andyrewco/mural:$VERSION
    container_name: mural-$VERSION
    env_file:
      - ".env"
    environment:
      - DATABASE_FILE=/go/src/app/mural.db
      - VERSION=v1.3.0
    volumes:
      - ./mural.db:/go/src/app/mural.db
    ports:
      - $PORT:1323
    networks:
      - mural_$VERSION

networks:
  mural_$VERSION:
    driver: bridge
