version: "3"
services:
  mural:
    image: andyrewco/mural:$VERSION
    deploy:
      replicas: 3
    environment:
      - DATABASE_FILE=/go/src/app/mural.db
      - VERSION=$VERSION
    volumes:
      - mural-data:/go/src/app/mural.db
    ports:
      - "1323:1323"

volumes:
  mural-data:
