version: "3"
services:
  mural:
    image: andyrewco/mural:$VERSION
    env_file:
      - ".env"
    environment:
      - DATABASE_FILE=/go/src/app/mural.db
      - VERSION=$VERSION
    volumes:
      - ./mural.db:/go/src/app/mural.db
    ports:
      - 1323:1323
