name: Build, Push And Deploy Beta

on:
  workflow_dispatch:
    inputs:
      verison:
        description: "The version of the beta release."
        required: true
        type: string

jobs:
  push_to_registry:
    name: Push To Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: beta

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: andyrewco/mural

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./code
          file: ./code/Dockerfile
          push: true
          tags: ${{ inputs.version }}
          labels: ${{ inputs.version }}

      - name: Replace $VERSION in mural.stack.yaml
        run: |
          export VERSION="${{ inputs.version }}"
          export PORT="1324"
          sed -i "s/\$VERSION/$VERSION/g" ./iac/mural.stack.yaml
          sed -i "s/\$PORT/$PORT/g" ./iac/mural.stack.yaml

      - name: Configure Swarm
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            rm -f /andrewnathan/mural-beta/mural.stack.yaml

      - name: Copy Files To Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./iac/mural.stack.yaml
          remote: /andrewnathan/mural/mural.stack.yaml
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          privateKey: ${{ secrets.SERVER_KEY }}

      - name: Configure Swarm
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /andrewnathan/mural
            docker compose -f mural.stack.yaml down
            docker compose -f mural.stack.yaml up -d
