name: Build, Push And Deploy

on:
  push:
  # release:
  #   types: [published]

jobs:
  build:
    name: Build File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Install dependencies
        run: |
          cd code
          go mod tidy
      - name: Build
        run: |
          cd code
          go build -o ./bin/mural main.go

      - name: Copy Files To Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./code/bin/mural
          remote: /andrewnathan/mural
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          privateKey: ${{ secrets.SERVER_KEY }}

      - name: Configure Swarm
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /andrewnathan/
            ls -a
